// examples/react/src/components/ConnectionBanner.tsx
import { useStore, useConnectionStatus } from '@laboverwire/stitch/react';
import { hasRemoteConfigured } from '../stitch.ts';

export function ConnectionBanner() {
  const { store, initialized, error } = useStore();
  const status = useConnectionStatus(store);

  const message = hasRemoteConfigured
    ? `Remote: ${status}`
    : 'Remote: disabled (set VITE_STITCH_SERVER_URL to enable)';

  return (
    <div className={`banner banner--${status}`}>
      <span>{initialized ? '✓ store ready' : '… initializing'}</span>
      <span>{message}</span>
      {error ? <span className="banner__error">{error.message}</span> : null}
    </div>
  );
}

// examples/vue/src/components/ConnectionBanner.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useStore, useConnectionStatus } from '@laboverwire/stitch/vue';
import { hasRemoteConfigured } from '../stitch.ts';

const ctx = useStore();
const status = useConnectionStatus(ctx.store);

const message = computed(() =>
  hasRemoteConfigured
    ? `Remote: ${status.value}`
    : 'Remote: disabled (set VITE_STITCH_SERVER_URL to enable)'
);
</script>

<template>
  <div :class="['banner', `banner--${status}`]">
    <span>{{ ctx.initialized ? '✓ store ready' : '… initializing' }}</span>
    <span>{{ message }}</span>
    <span v-if="ctx.error" class="banner__error">{{ ctx.error.message }}</span>
  </div>
</template>
