// examples/vue/src/components/ProjectView.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { useStore, useSyncScope, useEntitySnapshotAsMap } from '@laboverwire/stitch/vue';
import TaskList from './TaskList.vue';

const props = defineProps<{ projectId: string }>();
const ctx = useStore();
const { syncing, syncError, openScope } = useSyncScope(ctx.store, () => props.projectId);
const syncErrorMessage = computed(() => syncError.value?.message ?? '');

const projects = useEntitySnapshotAsMap(ctx.store, () => props.projectId, 'project');

const heading = computed(() => {
  const p = projects.value[props.projectId];
  return (p?.name as string) ?? props.projectId;
});

watch(
  () => [ctx.initialized, props.projectId] as const,
  ([ready, pid]) => {
    if (!ready || !pid) return;
    void openScope();
  },
  { immediate: true }
);
</script>

<template>
  <div class="project-view">
    <h2>{{ heading }}</h2>

    <p v-if="syncing">Opening scope…</p>
    <p v-if="syncError" class="error">{{ syncErrorMessage }}</p>

    <TaskList :project-id="projectId" />
  </div>
</template>

// examples/react/src/components/ProjectView.tsx
import { useEffect, useSyncExternalStore } from 'react';
import { useStore, useSyncScope } from '@laboverwire/stitch/react';
import type { Store } from '@laboverwire/stitch';
import { TaskList } from './TaskList.tsx';

interface Props {
  projectId: string;
}

function useProjectName(store: Store, projectId: string): string | null {
  return useSyncExternalStore(
    (onStoreChange) => store.subscribeToEntity('project', onStoreChange),
    () => {
      const project = store.read('project', projectId);
      if (!project) return null;
      return (project.name as string) ?? null;
    }
  );
}

export function ProjectView({ projectId }: Props) {
  const { store, initialized } = useStore();
  const { syncing, syncError, openScope } = useSyncScope(store, projectId);
  const projectName = useProjectName(store, projectId);

  useEffect(() => {
    if (!initialized) return;
    void openScope();
  }, [initialized, openScope]);

  return (
    <div className="project-view">
      <h2>{projectName ?? projectId}</h2>

      {syncing ? <p>Opening scope…</p> : null}
      {syncError ? <p className="error">{syncError.message}</p> : null}

      <TaskList projectId={projectId} />
    </div>
  );
}
